### ISSUE TITLE
Collision Objects, Double Jump

### ISSUE THREAD

**Issue by TSOA2** [ThePickleGawd/FPStudy#2]
Whenever jumping twice in the Terrorist Hunt, you start to fly. Interestingly, you can lower yourself with the control key, and you can "walk" faster (using the WASD keys) than if you were on the ground.

Also, (I'm not very experienced in Unity, so correct me if I'm wrong) if the player is never going to be able to reach the objects at the top of the buildings, why are the objects able to collide with the player?

Here's a picture of the player flying:
![Screen Shot 2021-12-18 at 9 18 22 AM](https://user-images.githubusercontent.com/91437753/146650418-c03cdec9-ed37-4b7f-b2fe-44a65da9936f.png)

**Comment by ThePickleGawd** [comment]
Yeah, flying is a feature I added in case you fall off of the starting building on accident. You can also wander around by flying, so it would be kinda weird if you could just fly through some objects. That's why they all have colliders. There's no performance issues especially since they are static objects without rigidbodies (used for physics).
